- name: Checkout source project
  git:
      repo: "{{ git_repo_url }}"
      dest: "{{ git_repo_checkout_dest }}"
      version: "{{ git_sha1 }}"
  become: yes

- name: Start ionic dev container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}"
    recreate: yes
    command: ionic-dev.sh serve
    volumes:
    - "{{ git_repo_ionic_src }}:/src"
    ports:
    - "9999:8100"

  register: output

- debug:
    var: output

- assert:
    that:
      - "docker_container.State.Running"